"use client";

import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

export default function Head() {
  const pathname = usePathname();

  const [title, setTitle] = useState("");

  useEffect(() => {
    if (pathname == "/") {
      setTitle("Home - NextFlix UK");
    } else if (pathname == "/about") {
      setTitle("About");
    } else if (pathname.startsWith("/tv")) {
      setTitle("TV Show Detail");
    } else if (pathname.startsWith("/movie")) {
      setTitle("Movie Detail");
    }
  }, [pathname]);
  return (
    <>
      <title>{title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </>
  );
}
